import type { ResumeProfile } from '../types';

/**
 * Infrastructure / cloud architect — AWS solution design, IaC, and on-prem DC.
 * Distinct from `architect` (app/system design) and `sre-devops` (SRE engineer).
 */
export const infraArchitect: ResumeProfile = {
	id: 'infra-architect',
	label: {
		pt: 'Arquiteto de Infra',
		en: 'Infrastructure Architect',
		es: 'Arquitecto de Infra',
	},
	description: {
		pt: 'Vagas de arquiteto de infraestrutura ou cloud — AWS, IaC, redes e datacenter.',
		en: 'Infrastructure or cloud architect roles — AWS, IaC, networking, and datacenter.',
		es: 'Roles de arquitecto de infraestructura o cloud — AWS, IaC, redes y datacenter.',
	},
	mode: 'recruiter',
	targetTitle: {
		pt: 'Arquiteto de Infraestrutura',
		en: 'Infrastructure Architect',
		es: 'Arquitecto de Infraestructura',
	},
	summaryFocus: [
		'infrastructure',
		'architecture',
		'aws',
		'iac',
		'networking',
		'datacenter',
		'cloud',
		'automation',
	],
	emphasizeSkills: [
		'AWS',
		'Terraform',
		'Docker',
		'Packer',
		'Ansible',
		'GitHub Actions',
		'CI/CD',
		'Linux',
		'Shell Script',
		'Distributed systems',
		'Scalability',
		'Resilience',
		'Elasticsearch',
		'Datadog',
		'Python',
		'Go',
	],
	deprioritizeSkills: [
		'Figma',
		'Playwright',
		'React',
		'NestJS',
		'C++',
		'Java',
		'Clean Code',
		'Design patterns',
	],
	experienceFocus: [
		'Nokia Networks',
		'Delivery Much Brasil',
		'Pagar.me',
		'Nuvemshop',
		'Globo.com',
	],
	maxExperienceItems: 5,
	extraKeywords: [
		'infrastructure architect',
		'cloud architect',
		'solution architecture',
		'AWS',
		'VPC',
		'IAM',
		'ECS',
		'Fargate',
		'EC2',
		'API Gateway',
		'ALB',
		'RDS',
		'ElastiCache',
		'SQS',
		'SNS',
		'S3',
		'CloudWatch',
		'Terraform',
		'Packer',
		'Ansible',
		'GitHub Actions',
		'OpenShift',
		'OpenStack',
		'datacenter',
		'networking',
		'IaC',
	],
};
