import type { PortfolioContent } from './types';

export const en: PortfolioContent = {
	meta: {
		title: 'Jonatas Pedraza — Software Engineer',
		description:
			'Software Engineer (Node.js, TypeScript, React, AWS): backend, frontend, architecture, and DevOps. Credit, payments, delivery, telecom, and video.',
	},
	nav: {
		about: 'About',
		experience: 'Experience',
		skills: 'Skills',
		contact: 'Contact',
		resume: 'Resume',
		resumeAts: 'ATS resume',
		versionPreview: 'Layout versions',
	},
	hero: {
		eyebrow: 'Jonatas Pedraza',
		headline: 'Software Engineer',
		tagline:
			'Backend, frontend, architecture, and cloud for products that must scale with reliability.',
		ctaContact: 'Get in touch',
		ctaResume: 'Download resume',
	},
	about: {
		title: 'About',
		body: 'Software Engineer with a path across backend, architecture, and DevOps, building platforms that must scale with reliability — credit, payments, delivery, telecom, video, and data-oriented products. I work end to end: from framing the problem and shaping the solution through implementation, observability, and production support. I am a generalist with judgment: choose the right tool for the challenge, keep architecture maintainable, and ship closely with product, design, and operations. I have experience using tools such as Codex, Claude, and Cursor in the daily engineering loop — with skills, rules, and MCPs to standardize context, speed up exploration, and raise delivery quality. I also plan and implement with Spec Kit and OpenSpec, turning intent into executable specs and cohesive changes, while still owning trade-offs, review, and what actually ships.',
		recruiter:
			'Software Engineer with 10+ years of experience across backend, architecture, cloud, and DevOps — plus recent frontend work (React/TypeScript). Experience on credit, payments, food delivery, telecom, and video platforms. Core stack: Node.js, TypeScript, NestJS, Python, Go, PostgreSQL, Redis, Elasticsearch, AWS, Docker, Terraform, and Datadog. Hands-on end to end: APIs, microservices, observability, and delivery with product and design. Hands-on with AI-assisted development tooling (Codex, Claude, Cursor; skills, rules, MCPs) and Spec Kit / OpenSpec for disciplined planning and delivery.',
	},
	experience: {
		title: 'Experience',
		items: [
			{
				company: 'Nuvemshop',
				companyUrl: 'https://www.nuvemshop.com.br/',
				role: 'Software Engineer',
				period: 'Mar 2024 — Present',
				location: 'São Paulo, Brazil',
				summary:
					'At Nuvemshop I evolve the credit platform — from offering and management through day-to-day operations. The work spans backend and frontend: I build scalable, reliable features, integrate partner APIs for the credit engine (system communication, data exchange, and automation of analysis and approval), and develop the credit frontend with React, TypeScript, Figma, and Playwright alongside design. In a lean squad with product, design, and operations, I also ship internal back-office tools that improve processes and speed up value delivery. When production breaks, I investigate with Datadog (metrics, logs, and root cause) and use generative AI tools as leverage in the development workflow — while still owning quality and what reaches the user.',
				highlights: [
					'Evolving the credit platform (offering, management, and operations) across backend and frontend',
					'Integrating partner APIs into the credit engine (analysis and approval flows)',
					'Building the credit frontend with React, TypeScript, Figma, and Playwright',
					'Shipping back-office tools for a lean product/design/operations squad',
					'Investigating production incidents with Datadog (metrics, logs, root cause)',
				],
				technologies: [
					'TypeScript',
					'Node.js',
					'React',
					'Figma',
					'Playwright',
					'PostgreSQL',
					'Redis',
					'AWS',
					'Datadog',
				],
			},
			{
				company: 'Delivery Much Brasil',
				companyUrl: 'https://www.deliverymuch.com.br/',
				role: 'Software Architect',
				period: 'Jun 2021 — Feb 2024',
				location: 'Santa Catarina, Brazil',
				summary:
					'As Software Architect at Delivery Much Brasil, I designed and led cloud solutions for food delivery as microservices on AWS, connecting business requirements to end-to-end architecture decisions: service boundaries, API contracts, persistence, and trade-offs across scale, performance, security, reliability, and cost. On the AWS platform I guided design around container compute and orchestration (ECS/Fargate and EC2 when it made sense), API exposure (API Gateway, ALB), managed data (RDS/PostgreSQL, ElastiCache/Redis, plus MongoDB and Elasticsearch in the solution ecosystem), messaging and decoupling (SQS/SNS), storage and artifacts (S3), identity and access (IAM), and observability (CloudWatch) — always with attention to networking (VPC, subnets, security groups) and continuous delivery. I created and evolved CI/CD pipelines with GitHub Actions to automate build, test, and deploy, reducing friction from code to production. I acted as the bridge between product and engineering — interviews, refinements, and stakeholder alignment — producing specs, diagrams, and guides to steer implementation and platform evolution. I defined and supported technical standards for teams (code, CI/CD, and agile practices), enabling tech leads to keep architectural coherence across squads. In critical moments I joined squads hands-on with legacy systems and complex integrations, unblocking high-priority deliveries without losing alignment to the target AWS architecture.',
				highlights: [
					'AWS solution architecture for food-delivery microservices (NestJS/Node.js/TypeScript, plus services in Go and Python), covering compute (ECS/Fargate, EC2), APIs (API Gateway, ALB), data (RDS, ElastiCache), messaging (SQS/SNS), S3, IAM, VPC, and CloudWatch',
					'Created and evolved CI/CD pipelines with GitHub Actions (build, test, and deploy)',
					'Translated business requirements into solution decisions: service boundaries, API contracts, persistence, and cost/performance/security trade-offs',
					'Architecture specs, diagrams, and guides to steer implementation and platform evolution',
					'Technical standards and tech-lead support (code, CI/CD, agile practices) for coherence across squads',
					'Hands-on in critical squads with legacy systems and complex integrations, unblocking delivery without breaking the target architecture',
					'Composed data and runtime stack (PostgreSQL/RDS, MongoDB, Redis/ElastiCache, Elasticsearch, Docker) aligned to domain load patterns',
				],
				technologies: [
					'NestJS',
					'Node.js',
					'TypeScript',
					'Go',
					'Python',
					'Docker',
					'AWS',
					'ECS',
					'Fargate',
					'EC2',
					'API Gateway',
					'ALB',
					'RDS',
					'ElastiCache',
					'SQS',
					'SNS',
					'S3',
					'IAM',
					'VPC',
					'CloudWatch',
					'GitHub Actions',
					'MongoDB',
					'PostgreSQL',
					'Redis',
					'Elasticsearch',
				],
			},
			{
				company: 'Pagar.me',
				companyUrl: 'https://www.pagar.me/',
				role: 'Software Engineer',
				period: 'Aug 2017 — Jun 2021',
				location: 'São Paulo, Brazil',
				summary:
					'On Pagar.me’s SRE team I worked on online payment systems under real availability and scale pressure. Day to day mixed architecture, development, and infrastructure evolution for distributed applications — including supporting squads on Elasticsearch cluster design and operations. I automated provisioning and delivery with Terraform, Packer, Ansible, and Docker on AWS, always aiming at the same outcomes: performance, reliability, and room to grow without production surprises.',
				highlights: [
					'SRE on online payment systems focused on availability and scale',
					'Architecture and infrastructure evolution for distributed applications',
					'Elasticsearch cluster design and operations with squad support: redesigned the read-layer cluster (dedicated nodes per workload, following Elastic best practices), cutting read-layer incidents by ~85%',
					'Automated provisioning and delivery with Terraform, Packer, Ansible, and Docker on AWS',
				],
				technologies: [
					'Python',
					'JavaScript',
					'Go',
					'C#',
					'AWS',
					'Terraform',
					'Packer',
					'Ansible',
					'Docker',
				],
			},
			{
				company: 'Nokia Networks',
				companyUrl: 'https://www.nokia.com/networks/',
				role: 'System Integration Engineer',
				period: 'Dec 2015 — Aug 2017',
				location: 'Rio de Janeiro, Brazil',
				summary:
					'At Nokia Networks I worked as a System Integration Engineer in on-prem datacenters for telecom operators, with end-to-end ownership of systems-infrastructure readiness and delivery: from defining the provisioning standard through on-site operational validation. I worked in corporate environments with rack/blade servers (Dell PowerEdge), datacenter networking, and heterogeneous stacks, designing and automating Nokia solution rollout with Packer, Ansible, Shell Script, SSH, and Linux — cutting the provisioning cycle from ~168 h (~7 days) to ~48 h (~2 days). When a site had no dedicated networking team, I led with the team the datacenter network provisioning (switches, ports, VLANs, and rack topology); physical expansion and hardware sizing were often executed by the vendor’s technical team, aligned to capacity requirements and service demand. Orchestration/virtualization in that project context was based on OpenShift (Red Hat) and OpenStack. With the team I produced field technical documentation — MOPs (Methods of Procedure), runbooks, installation and commissioning checklists, topology diagrams, and validation/rollback plans — to standardize execution, reduce operational risk, and ensure repeatability across sites. I also took part in IoT integrations and ETL pipelines (Greenplum and MySQL) connecting data sources to operational flows.',
				highlights: [
					'Standardized and automated systems-infrastructure provisioning in operator on-prem datacenters (Packer, Ansible, Shell, SSH, Linux), cutting the cycle from ~168 h to ~48 h',
					'Site operational readiness: integration and delivery of Nokia solutions on heterogeneous stacks, focused on repeatability, risk reduction, and time-to-ready',
					'Defined and executed datacenter network standards (VLANs, switches, ports, rack topology) when the site had no dedicated networking team',
					'Coordinated with the vendor (Dell PowerEdge rack/blade) on physical expansion/sizing aligned to service capacity demand',
					'Field operational-architecture documentation: MOPs, runbooks, installation/commissioning checklists, topology diagrams, and validation/rollback plans',
					'OpenShift and OpenStack as the environment’s orchestration/virtualization foundation',
					'IoT integrations and ETL pipelines (Greenplum, MySQL) for operational data flows',
				],
				technologies: [
					'Packer',
					'Ansible',
					'Shell Script',
					'SSH',
					'Linux',
					'OpenShift',
					'OpenStack',
					'MySQL',
					'Greenplum',
					'Elasticsearch',
					'Git',
				],
			},
			{
				company: 'Globo.com',
				companyUrl: 'https://www.globo.com/',
				role: 'Software Engineer',
				period: 'Nov 2014 — Nov 2015',
				location: 'Rio de Janeiro, Brazil',
				summary:
					'On Globo.com’s video platform I built and maintained backend services and APIs for live and on-demand delivery, focused on performance, scale, and resilience — where latency and stability truly matter. I also contributed to DevOps on automating and improving CI/CD pipeline efficiency, shortening the path from code to production. The work spanned microservices and distributed systems, with a data, cache, and load-balancing stack (PostgreSQL, MongoDB, Redis, Elasticsearch, Nginx) on top of Python, Node.js, and Docker.',
				highlights: [
					'Backend services and APIs for live and on-demand video delivery',
					'Focused on performance, scale, and resilience in microservices',
					'Built AI agents to detect video transmission failures; ~35% of open tickets were of that type, and with the agents we brought that share down to nearly zero',
					'Improved CI/CD pipelines with the DevOps team',
				],
				technologies: [
					'Python',
					'Node.js',
					'JavaScript',
					'Redis',
					'Docker',
					'PostgreSQL',
					'MongoDB',
					'Elasticsearch',
					'Nginx',
				],
			},
			{
				company: 'Neemu',
				companyUrl: 'https://www.linx.com.br/',
				role: 'Software Developer',
				period: 'Feb 2013 — Oct 2014',
				location: 'Manaus, Brazil',
				summary:
					'At Neemu I worked on the Big Data team building data-acquisition services for scalable, distributed systems — foundations that must absorb volume without losing reliability. I also joined DevOps, automating routines, improving continuous delivery/deployment pipelines, and managing AWS resources. Day to day mixed Node.js and JavaScript with MySQL, PostgreSQL, MongoDB, and Redis, plus Shell Script on Linux, Docker, and Git. I applied microservices, design patterns, and cloud practices so performance, scale, and maintainability stayed at the center of the decisions.',
				highlights: [
					'Data-acquisition services for distributed Big Data systems',
					'Automation and continuous delivery/deployment pipelines on AWS',
					'Node.js stack with MySQL, PostgreSQL, MongoDB, and Redis',
				],
				technologies: [
					'Node.js',
					'JavaScript',
					'MySQL',
					'PostgreSQL',
					'MongoDB',
					'Redis',
					'Docker',
					'AWS',
					'Shell Script',
				],
			},
			{
				company: 'INdT',
				companyUrl: 'https://indt.org.br/',
				role: 'Software Developer',
				period: 'Apr 2012 — Feb 2013',
				location: 'Manaus, Brazil',
				summary:
					'At INdT (Nokia Institute of Technology) I was on the Cloud & Backend team developing backend services and mobile applications. I built scalable REST APIs integrated with MySQL, using Node.js, JavaScript, Java, and C++ depending on the problem. Development and production ran on Linux, with heavy Shell Script use for automation. Projects demanded close collaboration with other teams, agile practices with Scrum, and continuous improvement of architecture and processes — with Git and design patterns keeping the codebase maintainable.',
				highlights: [
					'Scalable REST APIs and backend services on the Cloud & Backend team',
					'Mobile applications and MySQL integration',
					'Linux automation with Shell Script and agile practices (Scrum)',
				],
				technologies: [
					'Node.js',
					'JavaScript',
					'Java',
					'C++',
					'MySQL',
					'Linux',
					'Shell Script',
					'Git',
				],
			},
		],
	},
	skills: {
		title: 'Skills',
		groups: [
			{
				title: 'Backend & APIs',
				items: [
					'Node.js',
					'TypeScript',
					'NestJS',
					'Python',
					'Go',
					'C#',
					'REST',
					'Microservices',
				],
			},
			{
				title: 'Frontend',
				items: ['React', 'TypeScript', 'Playwright', 'Figma'],
			},
			{
				title: 'AI / DX',
				items: ['Cursor', 'Claude', 'Codex', 'MCP', 'Spec Kit', 'OpenSpec'],
			},
			{
				title: 'Architecture',
				items: [
					'Clean Code',
					'Clean Architecture',
					'Design patterns',
					'Distributed systems',
					'Scalability',
					'Resilience',
				],
			},
			{
				title: 'Cloud & DevOps',
				items: [
					'AWS',
					'Docker',
					'Terraform',
					'Packer',
					'Ansible',
					'CI/CD',
					'GitHub Actions',
					'Linux',
					'Shell Script',
				],
			},
			{
				title: 'Data & Observability',
				items: [
					'PostgreSQL',
					'MySQL',
					'MongoDB',
					'Redis',
					'Elasticsearch',
					'Datadog',
					'Metrics',
					'Logs',
				],
			},
		],
	},
	contributions: {
		title: 'Activity on GitHub',
		summary: '{total} public contributions in the last year.',
		profileLink: 'View GitHub profile',
		legendLabel: 'Activity level',
		legendLess: 'Less',
		legendMore: 'More',
		contributionSingular: 'contribution',
		contributionPlural: 'contributions',
	},
	contact: {
		title: 'Contact',
		body: 'Open to conversations about engineering, architecture, and opportunities. Prefer email or LinkedIn.',
		ctaEmail: 'Send email',
		labels: {
			email: 'Email',
			linkedin: 'LinkedIn',
			github: 'GitHub',
			location: 'Location',
		},
	},
	footer: {
		rights: 'Jonatas Pedraza. All rights reserved.',
		brandNote: 'Visual identity: Mandril Solutions',
	},
	wire: {
		role: 'role',
		name: 'name',
		summary: 'summary',
		activityGithub: 'activity / github',
		about: '01 / about',
		experience: '02 / experience',
		skills: '03 / skills',
	},
};
