import type { PortfolioContent } from './types';

export const es: PortfolioContent = {
	meta: {
		title: 'Jonatas Pedraza — Ingeniero de Software',
		description:
			'Ingeniero de Software (Node.js, TypeScript, React, AWS): backend, frontend, arquitectura y DevOps. Crédito, pagos, delivery, telecom y video.',
	},
	nav: {
		about: 'Sobre mí',
		experience: 'Experiencia',
		skills: 'Competencias',
		contact: 'Contacto',
		resume: 'Currículum',
		resumeAts: 'CV ATS',
		versionPreview: 'Versiones de layout',
	},
	hero: {
		eyebrow: 'Jonatas Pedraza',
		headline: 'Ingeniero de Software',
		tagline:
			'Backend, frontend, arquitectura y cloud para productos que deben escalar con confiabilidad.',
		ctaContact: 'Hablar conmigo',
		ctaResume: 'Descargar currículum',
	},
	about: {
		title: 'Sobre mí',
		body: 'Ingeniero de Software con trayectoria en backend, arquitectura y DevOps, construyendo plataformas que deben escalar con confiabilidad — crédito, pagos, delivery, telecom, video y productos orientados a datos. Trabajo de punta a punta: desde entender el problema y diseñar la solución hasta la implementación, observabilidad y soporte en producción. Perfil generalista con criterio: elijo la herramienta adecuada para el desafío, priorizo una arquitectura sostenible y colaboro de cerca con producto, diseño y operaciones. Tengo experiencia usando herramientas como Codex, Claude y Cursor en el flujo diario de ingeniería — con skills, rules y MCPs para estandarizar contexto, acelerar exploración y elevar la calidad de la entrega. También planifico e implemento con Spec Kit y OpenSpec, convirtiendo intención en specs ejecutables y cambios cohesivos, sin soltar el criterio sobre trade-offs, revisión y lo que realmente llega a producción.',
		recruiter:
			'Ingeniero de Software con más de 10 años de experiencia en backend, arquitectura, cloud y DevOps — y trabajo reciente también en frontend (React/TypeScript). Experiencia en plataformas de crédito, pagos, food delivery, telecom y video. Stack principal: Node.js, TypeScript, NestJS, Python, Go, PostgreSQL, Redis, Elasticsearch, AWS, Docker, Terraform y Datadog. Perfil hands-on de punta a punta: APIs, microservicios, observabilidad y entrega con producto y diseño. Experiencia práctica con herramientas de IA para desarrollo (Codex, Claude, Cursor; skills, rules, MCPs) y con Spec Kit / OpenSpec para planificar y entregar con rigor.',
	},
	experience: {
		title: 'Experiencia',
		items: [
			{
				company: 'Nuvemshop',
				companyUrl: 'https://www.nuvemshop.com.br/',
				role: 'Ingeniero de Software',
				period: 'Mar 2024 — Actual',
				location: 'São Paulo, Brasil',
				summary:
					'En Nuvemshop evoluciono la plataforma de crédito — desde la oferta y la gestión hasta las operaciones del día a día. El trabajo abarca backend y frontend: construyo funcionalidades escalables y confiables, integro APIs de socios para el motor de crédito (comunicación entre sistemas, intercambio de datos y automatización de análisis y aprobación) y desarrollo el frontend de crédito con React, TypeScript, Figma y Playwright, junto a diseño. En un squad reducido con producto, diseño y operaciones, también entrego herramientas internas de backoffice que mejoran procesos y aceleran valor. Cuando algo falla en producción, investigo con Datadog (métricas, logs y causa raíz) y uso herramientas de IA generativa como apalancamiento en el flujo de desarrollo — sin soltar la responsabilidad sobre calidad y lo que llega al usuario.',
				highlights: [
					'Evolución de la plataforma de crédito (oferta, gestión y operaciones) en backend y frontend',
					'Integración de APIs de socios en el motor de crédito (análisis y aprobación)',
					'Frontend de crédito con React, TypeScript, Figma y Playwright',
					'Herramientas de backoffice para un squad reducido (producto, diseño y operaciones)',
					'Investigación de incidentes en producción con Datadog (métricas, logs, causa raíz)',
				],
				technologies: [
					'TypeScript',
					'Node.js',
					'React',
					'Figma',
					'Playwright',
					'PostgreSQL',
					'Redis',
					'AWS',
					'Datadog',
				],
			},
			{
				company: 'Delivery Much Brasil',
				companyUrl: 'https://www.deliverymuch.com.br/',
				role: 'Arquitecto de Software',
				period: 'Jun 2021 — Feb 2024',
				location: 'Santa Catarina, Brasil',
				summary:
					'Como Software Architect en Delivery Much Brasil, diseñé y conduje soluciones cloud de food delivery en microservicios en AWS, conectando requisitos de negocio a decisiones de arquitectura de punta a punta: fronteras de servicio, contratos de API, persistencia y trade-offs de escala, rendimiento, seguridad, confiabilidad y costo. En la plataforma AWS, orienté el diseño en torno a compute y orquestación de contenedores (ECS/Fargate y EC2 cuando tenía sentido), exposición de APIs (API Gateway, ALB), datos gestionados (RDS/PostgreSQL, ElastiCache/Redis, además de MongoDB y Elasticsearch en el ecosistema de la solución), mensajería y desacoplamiento (SQS/SNS), almacenamiento y artefactos (S3), identidad y acceso (IAM) y observabilidad (CloudWatch) — siempre con atención a redes (VPC, subnets, security groups) y entrega continua. Creé y evolucioné pipelines de CI/CD con GitHub Actions para automatizar build, pruebas y deploy, reduciendo fricción entre código y producción. Actué como puente entre producto e ingeniería — entrevistas, refinamientos y alineaciones con stakeholders — produciendo especificaciones, diagramas y guías para orientar implementación y evolución. Definí y apoyé estándares técnicos para los equipos (código, CI/CD y prácticas ágiles), habilitando a tech leads a mantener coherencia arquitectónica entre squads. En momentos críticos entré hands-on en squads con legado e integraciones complejas, desbloqueando entregas de alta prioridad sin perder el alineamiento con la arquitectura objetivo en AWS.',
				highlights: [
					'Arquitectura de soluciones en AWS para food delivery en microservicios (NestJS/Node.js/TypeScript, además de servicios en Go y Python), cubriendo compute (ECS/Fargate, EC2), APIs (API Gateway, ALB), datos (RDS, ElastiCache), mensajería (SQS/SNS), S3, IAM, VPC y CloudWatch',
					'Creación y evolución de pipelines de CI/CD con GitHub Actions (build, pruebas y deploy)',
					'Traducción de requisitos de negocio en decisiones de solución: fronteras de servicio, contratos de API, persistencia y trade-offs de costo/rendimiento/seguridad',
					'Especificaciones, diagramas y guías de arquitectura para orientar implementación y evolución de la plataforma',
					'Estandarización técnica y apoyo a tech leads (código, CI/CD, prácticas ágiles) para coherencia entre squads',
					'Hands-on en squads críticos con legado e integraciones complejas, desbloqueando entregas sin romper la arquitectura objetivo',
					'Composición del stack de datos y runtime (PostgreSQL/RDS, MongoDB, Redis/ElastiCache, Elasticsearch, Docker) alineada a los patrones de carga del dominio',
				],
				technologies: [
					'NestJS',
					'Node.js',
					'TypeScript',
					'Go',
					'Python',
					'Docker',
					'AWS',
					'ECS',
					'Fargate',
					'EC2',
					'API Gateway',
					'ALB',
					'RDS',
					'ElastiCache',
					'SQS',
					'SNS',
					'S3',
					'IAM',
					'VPC',
					'CloudWatch',
					'GitHub Actions',
					'MongoDB',
					'PostgreSQL',
					'Redis',
					'Elasticsearch',
				],
			},
			{
				company: 'Pagar.me',
				companyUrl: 'https://www.pagar.me/',
				role: 'Ingeniero de Software',
				period: 'Ago 2017 — Jun 2021',
				location: 'São Paulo, Brasil',
				summary:
					'En el equipo de SRE de Pagar.me trabajé en sistemas de pagos online bajo presión real de disponibilidad y escala. El día a día mezclaba arquitectura, desarrollo y evolución de infraestructura para aplicaciones distribuidas — incluyendo apoyo a squads en el diseño y la operación de clusters Elasticsearch. Automatizé el aprovisionamiento y la entrega con Terraform, Packer, Ansible y Docker sobre AWS, siempre con el mismo norte: rendimiento, confiabilidad y capacidad de crecer sin sorpresas en producción.',
				highlights: [
					'SRE en sistemas de pagos online con foco en disponibilidad y escala',
					'Arquitectura y evolución de infraestructura para aplicaciones distribuidas',
					'Diseño y operación de clusters Elasticsearch con apoyo a squads: reformulé el cluster de la capa de lectura (nodos dedicados por operación, según buenas prácticas de Elastic), reduciendo incidentes en esa capa ~85%',
					'Automatización de aprovisionamiento y entrega con Terraform, Packer, Ansible y Docker en AWS',
				],
				technologies: [
					'Python',
					'JavaScript',
					'Go',
					'C#',
					'AWS',
					'Terraform',
					'Packer',
					'Ansible',
					'Docker',
				],
			},
			{
				company: 'Nokia Networks',
				companyUrl: 'https://www.nokia.com/networks/',
				role: 'Ingeniero de Integración de Sistemas',
				period: 'Dic 2015 — Ago 2017',
				location: 'Río de Janeiro, Brasil',
				summary:
					'En Nokia Networks actué como System Integration Engineer en datacenters on-premise de operadoras de telecom, con responsabilidad de punta a punta en la preparación y entrega de infraestructura de sistemas: desde la definición del estándar de aprovisionamiento hasta la validación operativa en sitio. Trabajé en entornos corporativos con servidores rack/blade (Dell PowerEdge), redes de datacenter y stacks heterogéneos, diseñando y automatizando el flujo de implantación de soluciones Nokia con Packer, Ansible, Shell Script, SSH y Linux — reduciendo el ciclo de aprovisionamiento de ~168 h (~7 días) a ~48 h (~2 días). En sitios sin equipo de redes dedicado, conduje con el equipo el aprovisionamiento de red (switches, puertos, VLANs y topología de rack); la expansión física y el dimensionamiento de hardware a menudo los ejecutaba el equipo técnico del fabricante, alineados a los requisitos de capacidad y demanda de los servicios. La plataforma de orquestación/virtualización en el contexto del proyecto se apoyó en OpenShift (Red Hat) y OpenStack. Con el equipo, produje documentación técnica de campo — MOPs (Methods of Procedure), runbooks, checklists de instalación y puesta en marcha, diagramas de topología y planes de validación/rollback — para estandarizar la ejecución, reducir el riesgo operativo y garantizar repetibilidad entre sitios. También participé en integraciones IoT y pipelines ETL (Greenplum y MySQL) conectando fuentes de datos a flujos operativos.',
				highlights: [
					'Estandarización y automatización del aprovisionamiento de infraestructura de sistemas en datacenters on-premise de operadoras (Packer, Ansible, Shell, SSH, Linux), reduciendo el ciclo de ~168 h a ~48 h',
					'Preparación operativa de sitios: integración y entrega de soluciones Nokia en stacks heterogéneos, con foco en repetibilidad, reducción de riesgo y tiempo hasta quedar listo para operar',
					'Definición y ejecución de estándares de red de datacenter (VLANs, switches, puertos, topología de rack) cuando el sitio no tenía equipo de redes dedicado',
					'Coordinación con el fabricante (Dell PowerEdge rack/blade) para expansión/dimensionamiento físico alineado a la demanda de capacidad de los servicios',
					'Documentación de arquitectura operativa de campo: MOPs, runbooks, checklists de instalación/puesta en marcha, diagramas de topología y planes de validación/rollback',
					'Plataformas OpenShift y OpenStack como base de orquestación/virtualización del entorno',
					'Integraciones IoT y pipelines ETL (Greenplum, MySQL) para flujos operativos de datos',
				],
				technologies: [
					'Packer',
					'Ansible',
					'Shell Script',
					'SSH',
					'Linux',
					'OpenShift',
					'OpenStack',
					'MySQL',
					'Greenplum',
					'Elasticsearch',
					'Git',
				],
			},
			{
				company: 'Globo.com',
				companyUrl: 'https://www.globo.com/',
				role: 'Software Engineer',
				period: 'Nov 2014 — Nov 2015',
				location: 'Río de Janeiro, Brasil',
				summary:
					'En la plataforma de video de Globo.com construí y mantuve servicios backend y APIs para entrega en vivo y bajo demanda, con foco en rendimiento, escala y resiliencia — donde latencia y estabilidad importan de verdad. También contribuí con el equipo de DevOps en la automatización y la eficiencia de los pipelines de CI/CD, acortando el camino del código a producción. El trabajo transitaba por microservicios y sistemas distribuidos, con stack de datos, caché y balanceo (PostgreSQL, MongoDB, Redis, Elasticsearch, Nginx) sobre Python, Node.js y Docker.',
				highlights: [
					'Servicios backend y APIs para entrega de video en vivo y bajo demanda',
					'Foco en rendimiento, escala y resiliencia en microservicios',
					'Creé agentes de IA para detectar fallos de transmisión en la plataforma de video; ~35% de los tickets abiertos eran de ese tipo y, con los agentes, redujimos esa proporción a casi cero',
					'Mejora de pipelines CI/CD con el equipo de DevOps',
				],
				technologies: [
					'Python',
					'Node.js',
					'JavaScript',
					'Redis',
					'Docker',
					'PostgreSQL',
					'MongoDB',
					'Elasticsearch',
					'Nginx',
				],
			},
			{
				company: 'Neemu',
				companyUrl: 'https://www.linx.com.br/',
				role: 'Software Developer',
				period: 'Feb 2013 — Oct 2014',
				location: 'Manaus, Brasil',
				summary:
					'En Neemu trabajé en el equipo de Big Data desarrollando servicios de adquisición de datos para sistemas escalables y distribuidos — bases que deben absorber volumen sin perder confiabilidad. También me sumé a DevOps, automatizando rutinas, mejorando pipelines de continuous delivery/deployment y operando recursos en AWS. El día a día mezclaba Node.js y JavaScript con MySQL, PostgreSQL, MongoDB y Redis, además de Shell Script en Linux, Docker y Git. Apliqué microservicios, patrones de diseño y prácticas de cloud para mantener rendimiento, escala y mantenibilidad en el centro de las decisiones.',
				highlights: [
					'Servicios de adquisición de datos para sistemas distribuidos de Big Data',
					'Automatización y pipelines de continuous delivery/deployment en AWS',
					'Stack Node.js con MySQL, PostgreSQL, MongoDB y Redis',
				],
				technologies: [
					'Node.js',
					'JavaScript',
					'MySQL',
					'PostgreSQL',
					'MongoDB',
					'Redis',
					'Docker',
					'AWS',
					'Shell Script',
				],
			},
			{
				company: 'INdT',
				companyUrl: 'https://indt.org.br/',
				role: 'Software Developer',
				period: 'Abr 2012 — Feb 2013',
				location: 'Manaus, Brasil',
				summary:
					'En el INdT (Instituto Nokia de Tecnología) formé parte del equipo de Cloud & Backend, desarrollando servicios backend y aplicaciones mobile. Construí APIs REST escalables integradas a MySQL, usando Node.js, JavaScript, Java y C++ según el problema. Los entornos de desarrollo y producción corrían en Linux, con fuerte uso de Shell Script para automatización. Los proyectos exigían colaboración cercana con otros equipos, prácticas ágiles con Scrum y mejora continua de arquitectura y procesos — con Git y design patterns sosteniendo la mantenibilidad del código.',
				highlights: [
					'APIs REST escalables y servicios backend en el equipo de Cloud & Backend',
					'Aplicaciones mobile e integración con MySQL',
					'Automatización en Linux con Shell Script y prácticas ágiles (Scrum)',
				],
				technologies: [
					'Node.js',
					'JavaScript',
					'Java',
					'C++',
					'MySQL',
					'Linux',
					'Shell Script',
					'Git',
				],
			},
		],
	},
	skills: {
		title: 'Competencias',
		groups: [
			{
				title: 'Backend & APIs',
				items: [
					'Node.js',
					'TypeScript',
					'NestJS',
					'Python',
					'Go',
					'C#',
					'REST',
					'Microservicios',
				],
			},
			{
				title: 'Frontend',
				items: ['React', 'TypeScript', 'Playwright', 'Figma'],
			},
			{
				title: 'AI / DX',
				items: ['Cursor', 'Claude', 'Codex', 'MCP', 'Spec Kit', 'OpenSpec'],
			},
			{
				title: 'Arquitectura',
				items: [
					'Clean Code',
					'Arquitectura limpia',
					'Design patterns',
					'Sistemas distribuidos',
					'Escalabilidad',
					'Resiliencia',
				],
			},
			{
				title: 'Cloud & DevOps',
				items: [
					'AWS',
					'Docker',
					'Terraform',
					'Packer',
					'Ansible',
					'CI/CD',
					'GitHub Actions',
					'Linux',
					'Shell Script',
				],
			},
			{
				title: 'Datos & Observabilidad',
				items: [
					'PostgreSQL',
					'MySQL',
					'MongoDB',
					'Redis',
					'Elasticsearch',
					'Datadog',
					'Métricas',
					'Logs',
				],
			},
		],
	},
	contributions: {
		title: 'Actividad en GitHub',
		summary: '{total} contribuciones públicas en el último año.',
		profileLink: 'Ver perfil en GitHub',
		legendLabel: 'Nivel de actividad',
		legendLess: 'Menos',
		legendMore: 'Más',
		contributionSingular: 'contribución',
		contributionPlural: 'contribuciones',
	},
	contact: {
		title: 'Contacto',
		body: 'Abierto a conversaciones sobre ingeniería, arquitectura y oportunidades. Prefiero email o LinkedIn.',
		ctaEmail: 'Enviar email',
		labels: {
			email: 'Email',
			linkedin: 'LinkedIn',
			github: 'GitHub',
			location: 'Ubicación',
		},
	},
	footer: {
		rights: 'Jonatas Pedraza. Todos los derechos reservados.',
		brandNote: 'Identidad visual: Mandril Solutions',
	},
	wire: {
		role: 'rol',
		name: 'nombre',
		summary: 'resumen',
		activityGithub: 'actividad / github',
		about: '01 / sobre mí',
		experience: '02 / experiencia',
		skills: '03 / competencias',
	},
};
