import type { PortfolioContent } from './types';

export const pt: PortfolioContent = {
	meta: {
		title: 'Jonatas Pedraza — Engenheiro de Software',
		description:
			'Engenheiro de Software (Node.js, TypeScript, React, AWS): backend, frontend, arquitetura e DevOps. Crédito, pagamentos, delivery, telecom e vídeo.',
	},
	nav: {
		about: 'Sobre',
		experience: 'Experiência',
		skills: 'Competências',
		contact: 'Contato',
		resume: 'Currículo',
		resumeAts: 'Currículo ATS',
		versionPreview: 'Versões de layout',
	},
	hero: {
		eyebrow: 'Jonatas Pedraza',
		headline: 'Engenheiro de Software',
		tagline:
			'Backend, frontend, arquitetura e cloud para produtos que precisam escalar com confiabilidade.',
		ctaContact: 'Fale comigo',
		ctaResume: 'Baixar currículo',
	},
	about: {
		title: 'Sobre',
		body: 'Engenheiro de Software com trajetória em backend, arquitetura e DevOps, construindo plataformas que precisam escalar com confiabilidade — crédito, pagamentos, delivery, telecom, vídeo e produtos orientados a dados. Atuo de ponta a ponta: do entendimento do problema e do desenho da solução à implementação, observabilidade e sustentação em produção. Perfil generalista com julgamento: escolho a ferramenta certa para o desafio, priorizo arquitetura sustentável e trabalho lado a lado com produto, design e operações. Tenho experiência com o uso de ferramentas como Codex, Claude e Cursor no fluxo diário de engenharia — com skills, rules e MCPs para padronizar contexto, acelerar exploração e elevar a qualidade da entrega. Também planejo e implemento com Spec Kit e OpenSpec, transformando intenção em specs executáveis e mudanças coesas, sem abrir mão do julgamento sobre trade-offs, revisão e o que de fato chega à produção.',
		recruiter:
			'Engenheiro de Software com 10+ anos de experiência em backend, arquitetura, cloud e DevOps — e atuação recente também em frontend (React/TypeScript). Experiência em plataformas de crédito, pagamentos, food delivery, telecom e vídeo. Stack principal: Node.js, TypeScript, NestJS, Python, Go, PostgreSQL, Redis, Elasticsearch, AWS, Docker, Terraform e Datadog. Perfil hands-on de ponta a ponta: APIs, microserviços, observabilidade e entrega com produto e design. Experiência prática com ferramentas de IA para desenvolvimento (Codex, Claude, Cursor; skills, rules, MCPs) e com Spec Kit / OpenSpec para planejar e entregar com rigor.',
	},
	experience: {
		title: 'Experiência',
		items: [
			{
				company: 'Nuvemshop',
				companyUrl: 'https://www.nuvemshop.com.br/',
				role: 'Software Engineer',
				period: 'Mar 2024 — Atual',
				location: 'São Paulo, Brasil',
				summary:
					'Na Nuvemshop atuo na evolução da plataforma de crédito — da oferta e gestão às operações do dia a dia. O trabalho atravessa backend e frontend: construo funcionalidades escaláveis e confiáveis, integro APIs de parceiros para o motor de crédito (comunicação entre sistemas, troca de dados e automação de análise e aprovação) e desenvolvo o frontend de crédito com React, TypeScript, Figma e Playwright, em parceria com design. Em um squad enxuto com produto, design e operações, também entrego ferramentas internas de backoffice que melhoram processos e aceleram valor. Quando algo quebra em produção, investigo com Datadog (métricas, logs e causa raiz) e uso ferramentas de IA generativa como alavancagem no fluxo de desenvolvimento — sem abrir mão da responsabilidade sobre qualidade e o que chega ao usuário.',
				highlights: [
					'Evolução da plataforma de crédito (oferta, gestão e operações) em backend e frontend',
					'Integração de APIs de parceiros no motor de crédito (análise e aprovação)',
					'Frontend de crédito com React, TypeScript, Figma e Playwright',
					'Ferramentas de backoffice para squad enxuto (produto, design e operações)',
					'Investigação de incidentes em produção com Datadog (métricas, logs, causa raiz)',
				],
				technologies: [
					'TypeScript',
					'Node.js',
					'React',
					'Figma',
					'Playwright',
					'PostgreSQL',
					'Redis',
					'AWS',
					'Datadog',
				],
			},
			{
				company: 'Delivery Much Brasil',
				companyUrl: 'https://www.deliverymuch.com.br/',
				role: 'Software Architect',
				period: 'Jun 2021 — Fev 2024',
				location: 'Santa Catarina, Brasil',
				summary:
					'Como Software Architect na Delivery Much Brasil, desenhei e conduzi soluções cloud de food delivery em microserviços na AWS, conectando requisitos de negócio a decisões de arquitetura de ponta a ponta: fronteiras de serviço, contratos de API, persistência e trade-offs de escala, performance, segurança, confiabilidade e custo. Na plataforma AWS, orientei o desenho em torno de compute e orquestração de containers (ECS/Fargate e EC2 quando fazia sentido), exposição de APIs (API Gateway, ALB), dados gerenciados (RDS/PostgreSQL, ElastiCache/Redis, além de MongoDB e Elasticsearch no ecossistema da solução), mensageria e desacoplamento (SQS/SNS), armazenamento e artefatos (S3), identidade e acesso (IAM) e observabilidade (CloudWatch) — sempre com atenção a redes (VPC, subnets, security groups) e entrega contínua. Criei e evoluí pipelines de CI/CD com GitHub Actions para automatizar build, testes e deploy, reduzindo atrito entre código e produção. Atuei como ponte entre produto e engenharia — entrevistas, refinamentos e alinhamentos com stakeholders — produzindo especificações, diagramas e guias para orientar implementação e evolução. Defini e apoiei padrões técnicos para os times (código, CI/CD e práticas ágeis), habilitando tech leads a manter coerência arquitetural entre squads. Em momentos críticos, entrei hands-on em squads com legado e integrações complexas, destravando entregas de alta prioridade sem perder o alinhamento com a arquitetura-alvo na AWS.',
				highlights: [
					'Arquitetura de soluções na AWS para food delivery em microserviços (NestJS/Node.js/TypeScript, além de serviços em Go e Python), cobrindo compute (ECS/Fargate, EC2), APIs (API Gateway, ALB), dados (RDS, ElastiCache), mensageria (SQS/SNS), S3, IAM, VPC e CloudWatch',
					'Criação e evolução de pipelines de CI/CD com GitHub Actions (build, testes e deploy)',
					'Tradução de requisitos de negócio em decisões de solução: fronteiras de serviço, contratos de API, persistência e trade-offs de custo/performance/segurança',
					'Especificações, diagramas e guias de arquitetura para orientar implementação e evolução da plataforma',
					'Padronização técnica e apoio a tech leads (código, CI/CD, práticas ágeis) para coerência entre squads',
					'Hands-on em squads críticos com legado e integrações complexas, destravando entregas sem romper a arquitetura-alvo',
					'Composição da stack de dados e runtime (PostgreSQL/RDS, MongoDB, Redis/ElastiCache, Elasticsearch, Docker) alinhada aos padrões de carga do domínio',
				],
				technologies: [
					'NestJS',
					'Node.js',
					'TypeScript',
					'Go',
					'Python',
					'Docker',
					'AWS',
					'ECS',
					'Fargate',
					'EC2',
					'API Gateway',
					'ALB',
					'RDS',
					'ElastiCache',
					'SQS',
					'SNS',
					'S3',
					'IAM',
					'VPC',
					'CloudWatch',
					'GitHub Actions',
					'MongoDB',
					'PostgreSQL',
					'Redis',
					'Elasticsearch',
				],
			},
			{
				company: 'Pagar.me',
				companyUrl: 'https://www.pagar.me/',
				role: 'Software Engineer',
				period: 'Ago 2017 — Jun 2021',
				location: 'São Paulo, Brasil',
				summary:
					'No time de SRE da Pagar.me trabalhei em sistemas de pagamentos online sob pressão de disponibilidade e escala. O dia a dia misturava arquitetura, desenvolvimento e evolução de infraestrutura para aplicações distribuídas — incluindo apoio a squads na operação e no desenho de clusters Elasticsearch. Automatizei provisionamento e entrega com Terraform, Packer, Ansible e Docker sobre AWS, sempre com o mesmo norte: performance, confiabilidade e capacidade de crescer sem surpresas em produção.',
				highlights: [
					'SRE em sistemas de pagamentos online com foco em disponibilidade e escala',
					'Arquitetura e evolução de infraestrutura para aplicações distribuídas',
					'Operação e desenho de clusters Elasticsearch com apoio a squads: reformulei o cluster da camada de leitura (nós dedicados por operação, alinhados às práticas da Elastic), reduzindo incidentes nessa camada em ~85%',
					'Automação de provisionamento e entrega com Terraform, Packer, Ansible e Docker na AWS',
				],
				technologies: [
					'Python',
					'JavaScript',
					'Go',
					'C#',
					'AWS',
					'Terraform',
					'Packer',
					'Ansible',
					'Docker',
				],
			},
			{
				company: 'Nokia Networks',
				companyUrl: 'https://www.nokia.com/networks/',
				role: 'System Integration Engineer',
				period: 'Dez 2015 — Ago 2017',
				location: 'Rio de Janeiro, Brasil',
				summary:
					'Na Nokia Networks atuei como System Integration Engineer em datacenters on-premise de operadoras de telecom, com responsabilidade de ponta a ponta na preparação e entrega de infraestrutura de sistemas: da definição do padrão de provisionamento à validação operacional em site. Trabalhei em ambientes corporativos com servidores rack/blade (Dell PowerEdge), redes de datacenter e stacks heterogêneos, desenhando e automatizando o fluxo de implantação de soluções Nokia com Packer, Ansible, Shell Script, SSH e Linux — reduzindo o ciclo de provisionamento de ~168 h (~7 dias) para ~48 h (~2 dias). Em sites sem equipe de redes dedicada, conduzi com o time o provisionamento de rede (switches, portas, VLANs e topologia de rack); a expansão física e o dimensionamento de hardware frequentemente eram executados pela equipe técnica do fabricante, alinhados aos requisitos de capacidade e demanda dos serviços. A plataforma de orquestração/virtualização no contexto do projeto apoiou-se em OpenShift (Red Hat) e OpenStack. Com a equipe, produzi documentação técnica de campo — MOPs (Methods of Procedure), runbooks, checklists de instalação e comissionamento, diagramas de topologia e planos de validação/rollback — para padronizar execução, reduzir risco operacional e garantir repetibilidade entre sites. Também participei de integrações IoT e pipelines ETL (Greenplum e MySQL) conectando fontes de dados a fluxos operacionais.',
				highlights: [
					'Padronização e automação do provisionamento de infraestrutura de sistemas em datacenters on-premise de operadoras (Packer, Ansible, Shell, SSH, Linux), cortando o ciclo de ~168 h para ~48 h',
					'Preparação operacional de sites: integração e entrega de soluções Nokia em stacks heterogêneos, com foco em repetibilidade, redução de risco e tempo até ficar pronto para operação',
					'Definição e execução de padrões de rede de datacenter (VLANs, switches, portas, topologia de rack) quando o site não tinha equipe de redes dedicada',
					'Coordenação com fabricante (Dell PowerEdge rack/blade) para expansão/dimensionamento físico alinhado à demanda de capacidade dos serviços',
					'Documentação de arquitetura operacional de campo: MOPs, runbooks, checklists de instalação/comissionamento, diagramas de topologia e planos de validação/rollback',
					'Plataformas OpenShift e OpenStack como base de orquestração/virtualização do ambiente',
					'Integrações IoT e pipelines ETL (Greenplum, MySQL) para fluxos operacionais de dados',
				],
				technologies: [
					'Packer',
					'Ansible',
					'Shell Script',
					'SSH',
					'Linux',
					'OpenShift',
					'OpenStack',
					'MySQL',
					'Greenplum',
					'Elasticsearch',
					'Git',
				],
			},
			{
				company: 'Globo.com',
				companyUrl: 'https://www.globo.com/',
				role: 'Software Engineer',
				period: 'Nov 2014 — Nov 2015',
				location: 'Rio de Janeiro, Brasil',
				summary:
					'Na plataforma de vídeo da Globo.com construí e mantive serviços backend e APIs para entrega ao vivo e sob demanda, com foco em performance, escala e resiliência — onde latência e estabilidade importam de verdade. Também contribuí com o time de DevOps na automação e na eficiência dos pipelines de CI/CD, encurtando o caminho do código à produção. O trabalho transitava por microserviços e sistemas distribuídos, com stack de dados, cache e balanceamento (PostgreSQL, MongoDB, Redis, Elasticsearch, Nginx) em cima de Python, Node.js e Docker.',
				highlights: [
					'Serviços backend e APIs para entrega de vídeo ao vivo e sob demanda',
					'Foco em performance, escala e resiliência em microserviços',
					'Criei agentes de IA para detectar falhas de transmissão na plataforma de vídeo; ~35% dos tickets abertos eram desse tipo e, com os agentes, reduzimos essa parcela para quase zero',
					'Melhoria de pipelines CI/CD com o time de DevOps',
				],
				technologies: [
					'Python',
					'Node.js',
					'JavaScript',
					'Redis',
					'Docker',
					'PostgreSQL',
					'MongoDB',
					'Elasticsearch',
					'Nginx',
				],
			},
			{
				company: 'Neemu',
				companyUrl: 'https://www.linx.com.br/',
				role: 'Software Developer',
				period: 'Fev 2013 — Out 2014',
				location: 'Manaus, Brasil',
				summary:
					'Na Neemu atuei no time de Big Data desenvolvendo serviços de aquisição de dados para sistemas escaláveis e distribuídos — o tipo de base que precisa absorver volume sem perder confiabilidade. Também integrei o time de DevOps, automatizando rotinas, melhorando pipelines de continuous delivery/deployment e operando recursos na AWS. O dia a dia misturava Node.js e JavaScript com MySQL, PostgreSQL, MongoDB e Redis, além de Shell Script em Linux, Docker e Git. Apliquei microserviços, padrões de projeto e práticas de cloud para manter performance, escala e manutenibilidade no centro das decisões.',
				highlights: [
					'Serviços de aquisição de dados para sistemas distribuídos de Big Data',
					'Automação e pipelines de continuous delivery/deployment na AWS',
					'Stack Node.js com MySQL, PostgreSQL, MongoDB e Redis',
				],
				technologies: [
					'Node.js',
					'JavaScript',
					'MySQL',
					'PostgreSQL',
					'MongoDB',
					'Redis',
					'Docker',
					'AWS',
					'Shell Script',
				],
			},
			{
				company: 'INdT',
				companyUrl: 'https://indt.org.br/',
				role: 'Software Developer',
				period: 'Abr 2012 — Fev 2013',
				location: 'Manaus, Brasil',
				summary:
					'No INdT (Instituto Nokia de Tecnologia) fiz parte do time de Cloud & Backend, desenvolvendo serviços backend e aplicações mobile. Construí APIs REST escaláveis integradas a MySQL, usando Node.js, JavaScript, Java e C++ conforme o problema pedia. Os ambientes de desenvolvimento e produção rodavam em Linux, com forte uso de Shell Script para automação. Os projetos exigiam colaboração próxima com outros times, práticas ágeis com Scrum e evolução contínua de arquitetura e processos — com Git e design patterns sustentando a manutenibilidade do código.',
				highlights: [
					'APIs REST escaláveis e serviços backend no time de Cloud & Backend',
					'Aplicações mobile e integração com MySQL',
					'Automação em Linux com Shell Script e práticas ágeis (Scrum)',
				],
				technologies: [
					'Node.js',
					'JavaScript',
					'Java',
					'C++',
					'MySQL',
					'Linux',
					'Shell Script',
					'Git',
				],
			},
		],
	},
	skills: {
		title: 'Competências',
		groups: [
			{
				title: 'Backend & APIs',
				items: [
					'Node.js',
					'TypeScript',
					'NestJS',
					'Python',
					'Go',
					'C#',
					'REST',
					'Microserviços',
				],
			},
			{
				title: 'Frontend',
				items: ['React', 'TypeScript', 'Playwright', 'Figma'],
			},
			{
				title: 'AI / DX',
				items: ['Cursor', 'Claude', 'Codex', 'MCP', 'Spec Kit', 'OpenSpec'],
			},
			{
				title: 'Arquitetura',
				items: [
					'Clean Code',
					'Arquitetura limpa',
					'Design patterns',
					'Sistemas distribuídos',
					'Escalabilidade',
					'Resiliência',
				],
			},
			{
				title: 'Cloud & DevOps',
				items: [
					'AWS',
					'Docker',
					'Terraform',
					'Packer',
					'Ansible',
					'CI/CD',
					'GitHub Actions',
					'Linux',
					'Shell Script',
				],
			},
			{
				title: 'Dados & Observabilidade',
				items: [
					'PostgreSQL',
					'MySQL',
					'MongoDB',
					'Redis',
					'Elasticsearch',
					'Datadog',
					'Métricas',
					'Logs',
				],
			},
		],
	},
	contributions: {
		title: 'Atividade no GitHub',
		summary: '{total} contribuições públicas no último ano.',
		profileLink: 'Ver perfil no GitHub',
		legendLabel: 'Nível de atividade',
		legendLess: 'Menos',
		legendMore: 'Mais',
		contributionSingular: 'contribuição',
		contributionPlural: 'contribuições',
	},
	contact: {
		title: 'Contato',
		body: 'Aberto a conversas sobre engenharia, arquitetura e oportunidades. Prefira e-mail ou LinkedIn.',
		ctaEmail: 'Enviar e-mail',
		labels: {
			email: 'E-mail',
			linkedin: 'LinkedIn',
			github: 'GitHub',
			location: 'Localização',
		},
	},
	footer: {
		rights: 'Jonatas Pedraza. Todos os direitos reservados.',
		brandNote: 'Identidade visual: Mandril Solutions',
	},
	wire: {
		role: 'cargo',
		name: 'nome',
		summary: 'resumo',
		activityGithub: 'atividade / github',
		about: '01 / sobre',
		experience: '02 / experiência',
		skills: '03 / competências',
	},
};
